name: video_stream
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # video player package for video stream from google community
  video_player: ^2.4.4

  # this is package for get, post method
  dio: ^4.0.6

  # date time parse
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:

  flutter_config: ^2.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg